language: ruby

env:
  - DB=postgres

before_script:
  - cp config/database.yml.travis config/database.yml
  - bundle exec rake db:setup

script: 'bundle exec rspec'

notifications:
  slack: walkant:LL2Wx3D6S15mHjF63NQLrUV5
