# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7c33da61b269af5ab67c9b894bd714b6a3c3b072badc666acc72300937822f8b0d65eb364867647a930b40f786e8b211eb5e32a7b878abdb43bb05c4b3f16d9d

test:
  secret_key_base: fd866eed862ad99cbab2ed037a22c0f92f3a7a54675a7693abab5434ddd78930228da1ae3c54e3d1d5071ced2e48061c253f4c05da7333bb5fc02592d2ec3a04

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
